name: Run Python Script and Push Files

on:
  schedule:
    # Run the job every week at midnight (00:00 UTC) on Sunday
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set executable permission for the bash script
      run: chmod +x build_package_info.sh

    - name: Run Bash script
      run: ./build_package_info.sh

    - name: Push output files
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add output/*
        git commit -m "Automated commit by GitHub Actions"
        git push origin HEAD:main
